// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XactJobs.TestModel.PostgreSql;

#nullable disable

namespace XactJobs.TestModel.PostgreSql.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XactJobs.TestModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("XactJobs.XactJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("text")
                        .HasColumnName("error_stack_trace");

                    b.Property<DateTime?>("ErrorTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("error_time");

                    b.Property<DateTime?>("LeasedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("leased_until");

                    b.Property<Guid?>("Leaser")
                        .HasColumnType("uuid")
                        .HasColumnName("leaser");

                    b.Property<string>("MethodArgs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method_args");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method_name");

                    b.Property<Guid?>("PeriodicJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("periodic_job_id");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("queue");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scheduled_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name");

                    b.HasKey("Id")
                        .HasName("pk_job");

                    b.HasIndex("PeriodicJobId")
                        .HasDatabaseName("ix_job_periodic_job_id");

                    b.HasIndex("Queue", "ScheduledAt")
                        .HasDatabaseName("ix_job_queue_scheduled_at");

                    b.ToTable("job", "xact_jobs");
                });

            modelBuilder.Entity("XactJobs.XactJobArchive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<string>("CronExpression")
                        .HasColumnType("text")
                        .HasColumnName("cron_expression");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("text")
                        .HasColumnName("error_stack_trace");

                    b.Property<DateTime?>("ErrorTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("error_time");

                    b.Property<string>("MethodArgs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method_args");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method_name");

                    b.Property<Guid?>("PeriodicJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("periodic_job_id");

                    b.Property<string>("PeriodicJobName")
                        .HasColumnType("text")
                        .HasColumnName("periodic_job_name");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("queue");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scheduled_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name");

                    b.HasKey("Id")
                        .HasName("pk_job_archive");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("ix_job_archive_completed_at");

                    b.ToTable("job_archive", "xact_jobs");
                });

            modelBuilder.Entity("XactJobs.XactJobPeriodic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MethodArgs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method_args");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("queue");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_job_periodic");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_job_periodic_name");

                    b.ToTable("job_periodic", "xact_jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
