DO $$
BEGIN
  IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'xact_jobs') THEN
      CREATE SCHEMA xact_jobs;
  END IF;
END $$;

-- ============================
-- Table storing scheduled jobs
-- ============================

CREATE TABLE xact_jobs.job (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  scheduled_at timestamptz NOT NULL,
  queue character varying(50) NOT NULL,
  leased_until timestamptz,
  leaser uuid,
  type_name text NOT NULL,
  method_name text NOT NULL,
  method_args text NOT NULL,
  periodic_job_id text,
  cron_expression text,
  error_count integer NOT NULL,
  CONSTRAINT pk_job PRIMARY KEY (queue, scheduled_at, id)
);

CREATE INDEX ix_job_leaser ON xact_jobs.job (leaser);

-- ===============================
-- Table storing execution history
-- ===============================

CREATE TABLE xact_jobs.job_history (
  id bigint NOT NULL,
  processed_at timestamptz NOT NULL,
  status integer NOT NULL,
  error_message text,
  error_stack_trace text,
  scheduled_at timestamptz NOT NULL,
  type_name text NOT NULL,
  method_name text NOT NULL,
  method_args text NOT NULL,
  queue text NOT NULL,
  periodic_job_id text,
  cron_expression text,
  error_count integer NOT NULL,
  CONSTRAINT pk_job_history PRIMARY KEY (id, processed_at)
);

CREATE INDEX ix_job_history_processed_at ON xact_jobs.job_history (processed_at);

-- ============================
-- Table storing recurring jobs
-- ============================

CREATE TABLE xact_jobs.job_periodic (
  id text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  cron_expression text NOT NULL,
  type_name text NOT NULL,
  method_name text NOT NULL,
  method_args text NOT NULL,
  queue text NOT NULL,
  is_active boolean NOT NULL,
  CONSTRAINT pk_job_periodic PRIMARY KEY (id)
);
